version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - frontend
      - frontend-develop
      - search
      # - search_api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  frontend:
    image: ghcr.io/nationalarchives/ds-frontend:feature-container-https
    # image: ghcr.io/nationalarchives/ds-frontend:24.11.11.798
    env_file:
      - .env
    environment:
      - ENVIRONMENT=staging
      - CONFIG=config.Staging
      - SECRET_KEY=${SECRET_KEY}
      - SENTRY_DSN=https://cd29dbbbe0df9acf5c001eb0da230525@o1230303.ingest.us.sentry.io/4507423798853632
      - SENTRY_JS=https://js.sentry-cdn.com/f736865f0e1fb140b8192082e1bfb5ad.min.js
      - WAGTAIL_API_URL=https://beta.nationalarchives.gov.uk/api/v2
      - COOKIE_DOMAIN=.dblclk.dev
      - CSP_IMG_SRC='self',https://tna.dblclk.dev,https://beta.nationalarchives.gov.uk,https://i.ytimg.com,https://www.googletagmanager.com
      - CSP_SCRIPT_SRC_ELEM='self',https://www.googletagmanager.com,https://*.sentry-cdn.com,https://www.youtube.com
      - CSP_STYLE_SRC='self',https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
      - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
      - CSP_CONNECT_SRC='self',https://*.google-analytics.com,https://*.sentry.io,https://noembed.com
      - CSP_MEDIA_SRC='self',https://beta.nationalarchives.gov.uk
      - CSP_WORKER_SRC='self',blob:,https://tna.dblclk.dev
      - CSP_FRAME_SRC='self',https://www.youtube-nocookie.com
      - CSP_FEATURE_PICTURE_IN_PICTURE='self',https://www.youtube-nocookie.com
      - FRAME_DOMAIN_ALLOW=https://beta.nationalarchives.gov.uk
      - CACHE_DEFAULT_TIMEOUT=10
      - GA4_ID=GTM-KX8ZWVZG
      - ALLOW_INSECURE=true
    # depends_on:
    #   - cms
    #   - search_api
    expose:
      - 8080
    # volumes:
    #   - ./certbot/conf/live/tna.dblclk.dev/fullchain.pem:/home/app/ssl/cert.pem
    #   - ./certbot/conf/live/tna.dblclk.dev/privkey.pem:/home/app/ssl/key.pem
  frontend-develop:
    image: ghcr.io/nationalarchives/ds-frontend:24.11.11.798
    env_file:
      - .env
    environment:
      - ENVIRONMENT=staging
      - CONFIG=config.Staging
      - SECRET_KEY=${SECRET_KEY}
      - SENTRY_DSN=https://cd29dbbbe0df9acf5c001eb0da230525@o1230303.ingest.us.sentry.io/4507423798853632
      - SENTRY_JS=https://js.sentry-cdn.com/f736865f0e1fb140b8192082e1bfb5ad.min.js
      - WAGTAIL_API_URL=https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/api/v2
      - COOKIE_DOMAIN=.dblclk.dev
      - CSP_IMG_SRC='self',https://develop.tna.dblclk.dev,https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site,https://*.nationalarchives.gov.uk,https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site,https://i.ytimg.com,https://img.youtube.com,https://www.googletagmanager.com,https://img.evbuc.com
      - CSP_SCRIPT_SRC_ELEM='self',https://www.googletagmanager.com,https://*.sentry-cdn.com,https://www.youtube.com,https://www.eventbrite.com
      - CSP_STYLE_SRC='self',https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
      - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
      - CSP_CONNECT_SRC='self',https://*.google-analytics.com,https://*.sentry.io,https://noembed.com
      - CSP_MEDIA_SRC='self',https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site
      - CSP_WORKER_SRC='self',blob:,https://develop.tna.dblclk.dev
      - CSP_FRAME_SRC='self',https://www.youtube-nocookie.com,https://www.eventbrite.com
      - CSP_FEATURE_PICTURE_IN_PICTURE='self',https://www.youtube-nocookie.com
      - FRAME_DOMAIN_ALLOW=https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site
      - CACHE_DEFAULT_TIMEOUT=10
      - CACHE_HEADER_DURATION=31536000
      - GA4_ID=GTM-KX8ZWVZG
      - FEATURE_LOGO_ADORNMENTS_CSS=https://develop.tna.dblclk.dev/enrichment/css/logo-adornments.css
    # depends_on:
    #   - cms
    #   - search_api
    expose:
      - 8080
  frontend-enrichment:
    image: ghcr.io/nationalarchives/ds-frontend-enrichment:24.11.05.5
    env_file:
      - .env
    environment:
      - ENVIRONMENT=staging
      - CONFIG=config.Staging
      - SECRET_KEY=${SECRET_KEY}
      - COOKIE_DOMAIN=.dblclk.dev
      - CACHE_DEFAULT_TIMEOUT=3600
      - CACHE_HEADER_DURATION=31536000
    expose:
      - 8080
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=etna
      - POSTGRES_DB=etna
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
  cms:
    image: ghcr.io/nationalarchives/ds-wagtail:24.09.17.509
    env_file:
      - .env
    environment:
      - ENVIRONMENT=staging
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - ALLOWED_HOSTS=develop.tna.dblclk.dev,tna.dblclk.dev,*
      - WAGTAILADMIN_BASE_URL=https://tna.dblclk.dev
      - CSRF_TRUSTED_ORIGIN=https://tna.dblclk.dev
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=etna
      - DATABASE_USER=etna
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_ENGINE=django.db.backends.postgresql
      - KONG_CLIENT_BASE_URL=https://aa83a1e6831944fa8bcf17f5ce391b73-58be9fd587cba13e.elb.eu-west-2.amazonaws.com/api/v1/data
      - KONG_IMAGE_PREVIEW_BASE_URL=https://ciim-media.s3.eu-west-2.amazonaws.com/preview/
      - KONG_CLIENT_KEY=${KONG_CLIENT_KEY}
      - KONG_CLIENT_VERIFY_CERTIFICATES=false
      - REDIS_URL=redis://:redis@redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - media:/app/media:rw
    expose:
      - 8080
  # search_api:
  #   image: ghcr.io/nationalarchives/ds-search-api:24.08.20.96
  #   env_file:
  #     - .env
  #   environment:
  #     - ENVIRONMENT=staging
  #     - CONFIG=config.Staging
  #     - SECRET_KEY=${SECRET_KEY}
  #     - SENTRY_DSN=https://3e24f4f474026e113e6dcdeccf2abded@o1230303.ingest.us.sentry.io/4507458864087040
  #     # - WAGTAIL_API_URL=http://cms:8080/api/v2
  #     - WAGTAIL_API_URL=https://develop-sr3snxi-rasrzs7pi6sd4.uk-1.platformsh.site/api/v2
  #     - ROSETTA_API_URL=http://afa13a7c0067b4f01991b0bad9e003a4-edf0e30af2b95f5f.elb.eu-west-2.amazonaws.com/api/v1
  #   # depends_on:
  #   #   - cms
  #   expose:
  #     - 8080
  search:
    image: ghcr.io/nationalarchives/ds-search:24.11.08.60
    env_file:
      - .env
    environment:
      - ENVIRONMENT=staging
      - DJANGO_SETTINGS_MODULE=config.settings.staging
      - ALLOWED_HOSTS=develop.tna.dblclk.dev,tna.dblclk.dev,*
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=etna
      - DATABASE_USER=etna
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_ENGINE=django.db.backends.postgresql
      - COOKIE_DOMAIN=.dblclk.dev
      - CSP_STYLE_SRC_ELEM='self',https://fonts.googleapis.com,https://p.typekit.net,https://use.typekit.net
      - CSP_FONT_SRC='self',https://fonts.gstatic.com,https://use.typekit.net
      - ROSETTA_API_URL=http://afa13a7c0067b4f01991b0bad9e003a4-edf0e30af2b95f5f.elb.eu-west-2.amazonaws.com/api/v1
    expose:
      - 8080
  # platform:
  #   container_name: platform
  #   build: ./platformsh
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_NAME=etna
  #     - DATABASE_USER=etna
  #     - PGPASSWORD=${POSTGRES_PASSWORD}
  #     - PLATFORM_PROJECT_ID=rasrzs7pi6sd4
  #     - PLATFORM_ENV=main
  #     - PLATFORMSH_CLI_TOKEN=${PLATFORMSH_CLI_TOKEN}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - db_backups:/home/app/db_backups:rw
  #     - media:/media:rw
  redis:
    container_name: redis
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass redis"
    ports:
      - 6379:6379
volumes:
  pgdata:
  media:
  db_backups:
