version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
      - /etc/keys/global.pass:/etc/keys/global.pass

  frontend:
    container_name: frontend
    image: ghcr.io/nationalarchives/national-archives-website-frontend:latest
    env_file:
      - .env
    environment:
      - WAGTAIL_API_URL=http://cms:8080/api/v2
      - WAGTAIL_MEDIA_URL=https://tna.dblclk.dev
      - SEARCH_API_URL=http://search:8080
    depends_on:
      - cms
      - search
    expose:
      - 8080

  db:
    container_name: db
    image: postgres:13.0

  cms:
    container_name: cms
    image: ghcr.io/nationalarchives/national-archives-website:develop
    volumes:
      - media:/media
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
    expose:
      - 8080

  search:
    container_name: saerch
    image: ghcr.io/nationalarchives/national-archives-search-api:latest
    depends_on:
      - cms
    env_file:
      - .env
    environment:
      - DISCOVERY_API_URL=https://discovery.nationalarchives.gov.uk/API/search/v1
      - WAGTAIL_API_URL=http://cms:8080/api/v2
    expose:
      - 8080
  
volumes:
  media:
