version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  frontend:
    container_name: frontend
    image: ghcr.io/nationalarchives/national-archives-website-frontend:latest
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - WAGTAIL_API_URL=http://cms:8080/api/v2
      - WAGTAIL_MEDIA_URL=https://tna.dblclk.dev
      - SEARCH_API_URL=http://search:8080
      - CACHE_DEFAULT_TIMEOUT=1
    depends_on:
      - cms
      - search
    expose:
      - 8080

  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=etna
      - POSTGRES_DB=etna
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432

  cms:
    container_name: cms
    image: ghcr.io/nationalarchives/national-archives-website:develop
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - WAGTAILADMIN_BASE_URL=https://tna.dblclk.dev/
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=etna
      - DATABASE_USER=etna
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_ENGINE=django.db.backends.postgresql
      - KONG_CLIENT_BASE_URL=https://aa83a1e6831944fa8bcf17f5ce391b73-58be9fd587cba13e.elb.eu-west-2.amazonaws.com/api/v1/data
      - KONG_IMAGE_PREVIEW_BASE_URL=https://ciim-media.s3.eu-west-2.amazonaws.com/preview/
      - KONG_CLIENT_KEY=${KONG_CLIENT_KEY}
      - KONG_CLIENT_VERIFY_CERTIFICATES=False
    depends_on:
      - postgres
    volumes:
      - media:/media
    expose:
      - 8080

  search:
    container_name: search
    image: ghcr.io/nationalarchives/national-archives-search-api:latest
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DISCOVERY_API_URL=https://discovery.nationalarchives.gov.uk/API/search/v1
      - WAGTAIL_API_URL=http://cms:8080/api/v2
    depends_on:
      - cms
    expose:
      - 8080

  platform:
    container_name: platform
    build: ./platformsh
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=etna
      - DATABASE_USER=etna
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PLATFORM_PROJECT_ID=rasrzs7pi6sd4
      - PLATFORM_ENV=develop
      - PLATFORMSH_CLI_TOKEN=${PLATFORMSH_CLI_TOKEN}
    depends_on:
      - postgres
    volumes:
      - db_backups:/app/db_backups:rw
      - media:/media:rw
  
volumes:
  pgdata:
  media:
  db_backups:
